# Introduction to text representation


### basically is the process to convert text into vectors by using Two famous technique BAG OF WORDS and TFIDF

1. what is feature Extraction from text?
2. why do we need it?
3. why is it difficult?
4. what is the core idea?
5. what are the techniques


1. Feature Extraction: As we know machine/algorithm can not understand the text data. It only understand number/maths. so
The process of converting text as number is called feature Extration.It it also called as text representation or text vectarization. 


It is to difficult to convert text as number. 
picture to number easy bacause picture has many pixel value, same for  speech but for text it is difficult
 

## Some technique 
### Machine Learning based approach
1. One Hot Encoding(Ohe)
2. Bag Of Word(Bow)
3. Ngrams
4. TFIDF
5. Custom Feature(self made)

### Some deep learning based approach
1. Word2Vec/Embedding (Word to Vector)


some common terms we have to know 
1.corpus(if we add all the data of any dataset this is called corpus)
2. vocabulary (Unique words of corpus )

## One hot encoding

## Flaws of One hot encoding

1.Sparsity.

2.No fixed size.

3.OOV(out of vocabulary).

4.No capturing of semantic meaning.

## Bag of Word implementation

In [54]:
import numpy as np
import pandas as pd


In [55]:
df=pd.DataFrame({'text':['People watch creator','creator watch creator','people write text','creator write text'],'output':[1,1,0,0]})

In [56]:
df

text  output
0   People watch creator       1
1  creator watch creator       1
2      people write text       0
3     creator write text       0

In [57]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
Bag_of_words=cv.fit_transform(df['text'])  

In [58]:
# printing the vocabulary
print(cv.vocabulary_)

{'people': 1, 'watch': 3, 'creator': 0, 'write': 4, 'text': 2}


In [59]:
# print the vector of first and 2nd row
print(Bag_of_words[0].toarray())
print(Bag_of_words[1].toarray())

[[1 1 0 1 0]]
[[2 0 0 1 0]]


In [60]:
cv.transform(['creator watch and creator write text']).toarray()
# as we can see here and is not count as one word because it is not in vocabulary. this is how it solve the out of vocabulary problem

array([[2, 0, 1, 1, 1]], dtype=int64)

# Disadvantage of bag of words
1. Sparsity
2. oov(it is not considering words which is not in vocabulary)
3. Ordering(bag of words does not consider order of word in a sentense. Thats why some times meaning of sentense changed)
4. let consider 2 sentense i: this is a very good answer 
ii: this is not very good answer. Bag of words consider these two sentense similar. but in reality these two sentense ar totally oposite to each other.


# N-grams 

#### using one hot encoding,bag of words we can not able to take ordering of words in consideration.N-grams solve this flaws . 
#### Key-concept: Combination of multiple words to create vocabulary or equences of N words used to capture more context than individual words. Includes unigrams, bigrams, and trigrams.

#### It can be bi-gram,tri-gram,quad-gram
bi-gram= 2 words,tri-grams=3 words etc

In [61]:
df 

text  output
0   People watch creator       1
1  creator watch creator       1
2      people write text       0
3     creator write text       0

In [62]:
cv=CountVectorizer(ngram_range=(2,2))
Bag_of_words=cv.fit_transform(df['text'])

print(cv.vocabulary_)
print(Bag_of_words[0].toarray())
print(Bag_of_words[1].toarray())


{'people watch': 2, 'watch creator': 4, 'creator watch': 0, 'people write': 3, 'write text': 5, 'creator write': 1}
[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]


In [63]:
#tri-grams
cv=CountVectorizer(ngram_range=(3,3))
Bag_of_words=cv.fit_transform(df['text'])

print(cv.vocabulary_)
print(Bag_of_words[0].toarray())
print(Bag_of_words[1].toarray())

{'people watch creator': 2, 'creator watch creator': 0, 'people write text': 3, 'creator write text': 1}
[[0 0 1 0]]
[[1 0 0 0]]


In [64]:
# combination of unigrams and bigrams
cv=CountVectorizer(ngram_range=(1,2))  # 1,2 means unigrams and bigrams
Bag_of_words=cv.fit_transform(df['text'])

print(cv.vocabulary_)
print(Bag_of_words[0].toarray())
print(Bag_of_words[1].toarray())

{'people': 3, 'watch': 7, 'creator': 0, 'people watch': 4, 'watch creator': 8, 'creator watch': 1, 'write': 9, 'text': 6, 'people write': 5, 'write text': 10, 'creator write': 2}
[[1 0 0 1 1 0 0 1 1 0 0]]
[[2 1 0 0 0 0 0 1 1 0 0]]


In [65]:
# #quad-grams 
# # it will show an error because no document exist with 4 word
# cv=CountVectorizer(ngram_range=(4,4))
# #Bag_of_words=cv.fit_transform(df['text'])

# print(cv.vocabulary_)
# print(Bag_of_words[0].toarray())
# print(Bag_of_words[1].toarray())

In [66]:
#length of text vocabulary
cv=CountVectorizer(analyzer='word',ngram_range=(1,1))
Bag_of_words=cv.fit_transform(df['text'])

print(len(cv.vocabulary_))


5


In [67]:
#length of text vocabulary for unigrams and bigrams
cv=CountVectorizer(analyzer='word',ngram_range=(1,2))
Bag_of_words=cv.fit_transform(df['text'])

print(len(cv.vocabulary_))

11


In [68]:
#length of text vocabulary for unigrams and bigrams
cv=CountVectorizer(analyzer='word',ngram_range=(1,2))
Bag_of_words=cv.fit_transform(df['text'])

print(len(cv.vocabulary_))

11


In [69]:
#length of text vocabulary for unigrams and bigrams and trigrams
cv=CountVectorizer(analyzer='word',ngram_range=(1,3))
Bag_of_words=cv.fit_transform(df['text'])

print(len(cv.vocabulary_))

15


## advantage
1. Able to capture semantic meaning of any sentense
2. Easy to implement and intuitive
## Disadvantage
1.  number of terms in vocabulary unigram< bi-grams< tri-grams thats mean slow because of more computionality(
    for above data frame 5 terms in vocabulary in unigrams on other hand 6 terms in vocabulary in bi_grams
)

# Tf-Idf(Term Frequency-Inverse Document Frequency)

##### A weighting scheme that measures the importance of a word in a document relative to a collection of documents (corpus).

TF=Number of occurance of term t in document d/ total number of terms in the document d

IDF= loge (total number of documents in the corpus)/(number of document with term t in them)

In [70]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.49681612, 0.61366674, 0.        , 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.        , 0.61366674, 0.        , 0.61366674]])

In [71]:
print(tfidf.vocabulary_)
print(tfidf.idf_)

{'people': 1, 'watch': 3, 'creator': 0, 'write': 4, 'text': 2}
[1.22314355 1.51082562 1.51082562 1.51082562 1.51082562]


# Things before to learn word2vec

#### Word Embeddings

Definition:Word embedding is a way of representing words as numerical vectors (lists of numbers) in a continuous, high-dimensional space so that words with similar meanings are located near each other.


his allows algorithms to understand relationships such as:
Semantic similarity: “king” is close to “queen”.
Analogies: “Paris – France ≈ Tokyo – Japan”.

#### Types :
1.Frequency based
    i.bag of words
    ii. tf-idf
    iii.glove(global vector)
    iv.maxtrix factorization
2.Prediction based
   i.Word2Vec

#### What is word2vec?
it is a word embedding technique.

#### Main advantage:
1. we can find or capture  semantic meaning of words. like beautiful and nice these two are similar words.

2.Unlike tf-idf,bag of words word2vec create less dimension of vector. tf-idf,bag of words =n dimension but in word2vec maintained it within 100-300 dimension of vector.

3. Dense vector( more non zero element in vector). This reduce overfitting.


#### Two way to acheive it
1. Pre trained(Pre-trained vectors trained on a part of the Google News dataset (about 100 billion words). The model contains 300-dimensional vectors for 3 million words and phrases.)
2. Self trained

In [72]:
import gensim
from gensim.models import Word2Vec,keyedvectors

In [73]:
model=keyedvectors.load_word2vec_format(r"C:\Users\mdans\Downloads\GoogleNews-vectors-negative300.bin\GoogleNews-vectors-negative300.bin",binary=True,limit=100000)

In [74]:
model['man'].shape

(300,)

In [75]:
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [76]:
model.most_similar('man')

[('woman', 0.7664011716842651),
 ('boy', 0.6824870109558105),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('robber', 0.5585119128227234),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116),
 ('guy', 0.5420035719871521),
 ('person', 0.5342026352882385)]

In [77]:
model.most_similar('facebook')

[('Facebook', 0.7563533186912537),
 ('twitter', 0.6988552212715149),
 ('Twitter', 0.664244532585144),
 ('Facebook.com', 0.6529868841171265),
 ('facebook.com', 0.6135972142219543),
 ('Twitter.com', 0.6102108359336853),
 ('Myspace', 0.5829181671142578),
 ('Youtube', 0.5796944499015808),
 ('social_networking', 0.5592854022979736),
 ('social_networking_sites', 0.5527533292770386)]

In [78]:
model.similarity('man','woman')

0.76640123

In [79]:
model.similarity('woman','drunk')

0.31487936

In [80]:
model.similarity('man','drunk')

0.32602543

In [81]:
model.similarity('man','programming')

-0.06693381

In [82]:
model.similarity('woman','programming')

-0.034060806

In [83]:
model.doesnt_match(['man','woman','drunk'])

'drunk'

In [84]:
vector=model['king']-model['man']+model['woman']
model.most_similar([vector])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613664388656616),
 ('sultan', 0.5376776456832886),
 ('queens', 0.5289887189865112),
 ('ruler', 0.5247419476509094)]

##### The underlying assumption of word2vec is that two words sharing similar contexts also share a similar meaning and consequently a similar vector representation from a model.

### Types of Word2Vec
1. CBOw(continuous bag of words)
2. Skip gram

both are neural network(shallow)

### Train self Word2Vec model
Using game of thrones book data

In [85]:
import numpy as np
import pandas as pd
import gensim
import os

In [86]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\mdans\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [87]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

story=[]
for  filename in os.listdir(r"C:\Users\mdans\Downloads\gameofthrones" ):
   
   file = open(os.path.join(r'C:\Users\mdans\Downloads\gameofthrones', filename ,), 'r', encoding='cp1252')
   corpus=file.read()
   sentences= sent_tokenize(corpus)
   for sentence in sentences:
        story.append(simple_preprocess(sentence))

In [88]:
# story

In [89]:
#length of story
len(story)

145020

#### Model creation

In [90]:
self_model=gensim.models.Word2Vec(window=10,min_count=2)

In [91]:
#building vocabulary
self_model.build_vocab(story)

In [92]:
#training the model
self_model.train(story,total_examples=self_model.corpus_count,epochs=self_model.epochs)

(6570448, 8628190)

In [93]:
self_model.wv.most_similar('king')

[('baratheon', 0.6808120608329773),
 ('realm', 0.6712384223937988),
 ('prince', 0.666652262210846),
 ('throne', 0.6360361576080322),
 ('usurper', 0.6179081201553345),
 ('conqueror', 0.6153979897499084),
 ('tourney', 0.6086326837539673),
 ('battle', 0.6044253706932068),
 ('dragonstone', 0.6007109880447388),
 ('targaryen', 0.5940443277359009)]

In [94]:
self_model.wv.most_similar('daenerys')

[('stormborn', 0.8269252777099609),
 ('targaryen', 0.7575649619102478),
 ('unburnt', 0.7344520092010498),
 ('princess', 0.7343717217445374),
 ('elia', 0.7249239683151245),
 ('myrcella', 0.7205745577812195),
 ('queen', 0.7114650011062622),
 ('margaery', 0.7008574604988098),
 ('viserys', 0.6931341290473938),
 ('martell', 0.6579175591468811)]

In [95]:
self_model.wv.doesnt_match(['jon','rikon','robb','sansa','arya'])

'jon'

In [96]:
# vector of particular word
self_model.wv['jon']

array([-0.4778681 , -1.3247433 , -0.1001518 , -0.7737016 ,  0.28544903,
       -0.0100521 ,  1.2187394 , -0.03966114, -1.1336316 ,  0.27926144,
       -1.5103897 ,  0.6390375 ,  0.54569554, -0.59516406, -0.13867696,
        0.58939797,  1.7522539 ,  3.228509  ,  1.9699223 , -0.84508914,
        2.190869  , -2.5670383 ,  0.5692317 ,  0.23228401,  0.662764  ,
       -1.2117636 ,  1.2587128 ,  0.5763529 ,  0.54868793,  0.76277053,
       -1.9769746 , -0.10058395,  2.3100474 , -0.8622819 ,  1.4626132 ,
        0.6305116 ,  3.2408166 ,  0.05250947,  0.84984106, -1.2084628 ,
       -0.63824105, -1.108271  , -0.79432434,  2.237662  ,  1.6134934 ,
       -3.1927083 , -0.42352283,  0.58948296, -1.934679  , -0.20428306,
       -0.07341302, -0.26864412,  2.3025358 , -0.65068656, -0.30116156,
       -0.49398538, -0.31786764, -2.0894382 , -0.33548763,  0.14469579,
        1.426911  ,  0.44850543,  0.5618789 , -0.96998966, -0.18145981,
       -0.20573421, -0.05918689,  2.7323349 , -0.47652006,  0.65

In [97]:
#similarity between two words
self_model.wv.similarity('arya','sansa')

0.8343269

In [98]:
# vector of all words and its shape (unique words)
self_model.wv.get_normed_vectors().shape


(17453, 100)

In [99]:
#index to word( corresponding unique words of individual vector)
self_model.wv.index_to_key

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'lord',
 'them',
 'no',
 'from',
 'would',
 'were',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'we',
 'could',
 'are',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'king',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'who',
 'down',
 'well',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'father',
 'old',
 'hand',
 'even',
 'too',
 'tyrion',
 'before',
 'never',
 'an',
 'off',
 'see',
 'know',
 'into',
 'made',
 'now',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'then',
 'how',
 'long',
 'has',
 'can',
 'might',
 'us',
 'come',
 'where',
 'here',
 'through',
 'still',
 'face',
 'head',
 'red',
 'll',
 'way',
 'boy',
 'page',
 'must',
 'once',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 

#### plot some graph of the vector

since it has 100 dimension we can't plot it in graph.
dimentionality reduction (PCA) techniques helps to plot graph by reducing the dimension.

In [100]:
!pip install scikit-learn

In [101]:
from sklearn.decomposition import PCA
# number of components means dimension
pca=PCA(n_components=3)
x=pca.fit_transform(self_model.wv.get_normed_vectors())
x.shape

(17453, 3)

In [102]:
import plotly.express as px
fig=px.scatter_3d(x[:100],x=0,y=1,z=2,color= self_model.wv.index_to_key[:100])
fig.show()

In [103]:
# plot between 200 to 300
fig=px.scatter_3d(x[200:300],x=0,y=1,z=2,color= self_model.wv.index_to_key[200:300])
fig.show()