#### classification
i. Binary classification
ii. Multi-class classification
iii. multi-level classification

#### Examples of text classification
1. Email spam classification.
2. Sentiment Analysis.
3. Language Detection.
4. Fake news Detection.

#### Pipeline of Text Classification
Data acquisation--> text preprocessing--> Text Vectarization(Bow,tf-idf,Word2Vec)-->  Modeling([Ml_based=Naive Bayes,Random foreswt],[Dl-based=RNN(LSTM), CNN, BERT(pre-trained model) ]) -->  Evaluation(accuracy score,confusion martrix)--> Deploy

#### Different Approaches 
1. Heuristic approach( manual approach.This approach used when data are too small)
2. API's
3. ML
4. DL

In [2]:
import numpy as np
import pandas as pd

In [3]:
temp_df=pd.read_csv(r"C:\Users\mdans\Downloads\archive (6)\IMDB Dataset.csv")

In [4]:
temp_df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
# take 10000 data for lack of resources
df=temp_df.iloc[:10000 ]

In [6]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. <br /><br />The...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[10000 rows x 2 columns]

In [7]:
# value count
df['sentiment'].value_counts()
# we have nearly 5000 positive and 5000 negative. so dataset is balanced

sentiment
positive    5028
negative    4972
Name: count, dtype: int64

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
# see duplicate data
df.duplicated().sum()

17

In [10]:
# as we have duplicate data so we will drop it
df.drop_duplicates(inplace=True)

C:\Users\mdans\AppData\Local\Temp\ipykernel_11128\2173366090.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)


In [11]:
df.duplicated().sum()

0

#### Basic Pre-processing
1. Remove tags
2. Remove stopwords
3. Lower casing


In [12]:
import re
def remove_html_tags(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'',text)
df['review'] = df['review'].apply(remove_html_tags)

C:\Users\mdans\AppData\Local\Temp\ipykernel_11128\1372049680.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(remove_html_tags)


In [13]:
df

review sentiment
0     One of the other reviewers has mentioned that ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought this was a wonderful way to spend ti...  positive
3     Basically there's a family where a little boy ...  negative
4     Petter Mattei's "Love in the Time of Money" is...  positive
...                                                 ...       ...
9995  Fun, entertaining movie about WWII German spy ...  positive
9996  Give me a break. How can anyone say that this ...  negative
9997  This movie is a bad movie. But after watching ...  negative
9998  This is a movie that was probably made to ente...  negative
9999  Smashing film about film-making. Shows the int...  positive

[9983 rows x 2 columns]

Removing Stops words

In [14]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mdans\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
# def remove_stopwords(text):
#     new_text=[]
#     for word in text.split():
#         if word in stopwords.words("english"):
#             new_text.append('')
#         else:
#             new_text.append(word)
#     x=new_text[:]
#     new_text.clear()
#     return " ".join(x)
from nltk.corpus import stopwords
sw_list = stopwords.words('english')
df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))




C:\Users\mdans\AppData\Local\Temp\ipykernel_11128\4292844889.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].apply(lambda x: [item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))


In [19]:
df

review sentiment
0     One reviewers mentioned watching 1 Oz episode ...  positive
1     A wonderful little production. The filming tec...  positive
2     I thought wonderful way spend time hot summer ...  positive
3     Basically there's family little boy (Jake) thi...  negative
4     Petter Mattei's "Love Time Money" visually stu...  positive
...                                                 ...       ...
9995  Fun, entertaining movie WWII German spy (Julie...  positive
9996  Give break. How anyone say "good hockey movie"...  negative
9997  This movie bad movie. But watching endless ser...  negative
9998  This movie probably made entertain middle scho...  negative
9999  Smashing film film-making. Shows intense stran...  positive

[9983 rows x 2 columns]

Lower casing 

In [20]:
# lower casing 
df['review'] = df['review'].str.lower()

C:\Users\mdans\AppData\Local\Temp\ipykernel_11128\250224482.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['review'] = df['review'].str.lower()


In [ ]:
df

review sentiment
0     one    reviewers  mentioned   watching  1 oz e...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought    wonderful way  spend time    hot ...  positive
3     basically there's  family   little boy (jake) ...  negative
4     petter mattei's "love   time  money"   visuall...  positive
...                                                 ...       ...
9995  fun, entertaining movie  wwii german spy (juli...  positive
9996  give   break. how  anyone say     "good hockey...  negative
9997  this movie   bad movie. but  watching  endless...  negative
9998  this   movie   probably made  entertain  middl...  negative
9999  smashing film  film-making. shows  intense  st...  positive

[9983 rows x 2 columns]

Feature separation

In [42]:
x = df.iloc[:,0:1]
y = df['sentiment']

In [43]:
x

review
0     one reviewers mentioned watching 1 oz episode ...
1     a wonderful little production. the filming tec...
2     i thought wonderful way spend time hot summer ...
3     basically there's family little boy (jake) thi...
4     petter mattei's "love time money" visually stu...
...                                                 ...
9995  fun, entertaining movie wwii german spy (julie...
9996  give break. how anyone say "good hockey movie"...
9997  this movie bad movie. but watching endless ser...
9998  this movie probably made entertain middle scho...
9999  smashing film film-making. shows intense stran...

[9983 rows x 1 columns]

In [44]:
#label encode y
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

array([1, 1, 1, ..., 0, 0, 1])

In [45]:
# train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [46]:
x_train.shape

(7986, 1)

In [49]:
# vectorization
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000)

X_train_bow = cv.fit_transform(x_train['review']).toarray()
X_test_bow = cv.transform(x_test['review']).toarray()


In [52]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
gnb.fit(X_train_bow,y_train)
y_pred=gnb.predict(X_test_bow)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7636454682023035

In [59]:
#confiusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[783, 202],
       [169, 843]], dtype=int64)

In [56]:
cv=CountVectorizer(max_features=1000)

X_train_bow = cv.fit_transform(x_train['review']).toarray()
X_test_bow = cv.transform(x_test['review']).toarray()

In [57]:
gnb=GaussianNB()
gnb.fit(X_train_bow,y_train)
y_pred=gnb.predict(X_test_bow)

accuracy_score(y_test,y_pred)

0.814221331997997

In [58]:
#confiusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[783, 202],
       [169, 843]], dtype=int64)

Using Random Forest Classifier


In [60]:
#random forest
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train_bow,y_train)
y_pred=rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8202303455182774

Using Tf-idf


In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
x_train_tfidf=tfidf.fit_transform(x_train['review'])
x_test_tfidf=tfidf.transform(x_test['review'])

In [62]:
#Random forest

rf=RandomForestClassifier()
rf.fit(x_train_tfidf,y_train)
y_pred=rf.predict(x_test_tfidf)
accuracy_score(y_test,y_pred)

0.8537806710065098

using Word2Vec with self trained model

In [68]:
df

review sentiment
0     one reviewers mentioned watching 1 oz episode ...  positive
1     a wonderful little production. the filming tec...  positive
2     i thought wonderful way spend time hot summer ...  positive
3     basically there's family little boy (jake) thi...  negative
4     petter mattei's "love time money" visually stu...  positive
...                                                 ...       ...
9995  fun, entertaining movie wwii german spy (julie...  positive
9996  give break. how anyone say "good hockey movie"...  negative
9997  this movie bad movie. but watching endless ser...  negative
9998  this movie probably made entertain middle scho...  negative
9999  smashing film film-making. shows intense stran...  positive

[9983 rows x 2 columns]

In [69]:
import gensim 
from nltk import sent_tokenize
from gensim.utils import simple_preprocess


In [ ]:
#corpus building
story = []
for doc in df['review']:
    raw_sent = sent_tokenize(doc)
    for sentence in raw_sent:
        story.append(simple_preprocess(sentence))

In [76]:
#model creation
#by default dimension=100
self_model = gensim.models.Word2Vec(window=10,min_count=2)


In [79]:
#building vocabulary
self_model.build_vocab(story)

#training model
self_model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(6084112, 6514535)

In [82]:
#check the length of vocabulary
len(self_model.wv.index_to_key)

31845

In [86]:
def document_vector(doc):
    # remove out-of-vocabulary words
    doc = [word for word in doc.split() if word in self_model.wv.index_to_key]
    return np.mean(self_model.wv[doc], axis=0)

In [87]:
from tqdm import tqdm
X = []
for doc in tqdm(df['review'].values):
    X.append(document_vector(doc))

100%|██████████| 9983/9983 [12:01<00:00, 13.83it/s]   


In [89]:
#convert X to numpy array
X = np.array(X)
X.shape

(9983, 100)

In [91]:
# label encode y 
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y = encoder.fit_transform(df['sentiment'])
y

array([1, 1, 1, ..., 0, 0, 1])

In [93]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [94]:
#random forest classifier
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred=rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.7761642463695543