#### Word Embedding Layers steps
1. One hot encoding
2. Padding on ohe value (one hot encoding) to make sentense of same dimension because machine learning model need fixed size of data
   

*   Post padding
*   Pre padding

3. Convert ohe value into vector





In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [21]:
sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [22]:
### vocabulary size
voc_size=500  # it can be change

In [23]:
# One Hot Representation

one_hot_repre=[one_hot(words,voc_size) for words in sent]

print(one_hot_repre)

[[257, 251, 85, 56, 223, 186], [78, 201, 85, 348, 70, 211], [469, 175, 240, 169], [257, 121, 85, 82, 257, 346], [44, 187, 424, 85, 348, 70, 211], [488, 85, 348, 70, 177, 288]]


In [24]:
# word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [38]:
## pre padding
sent_length=8
# embedding
embedded_docs=pad_sequences(one_hot_repre,padding='pre',maxlen=sent_length)


In [39]:
print(embedded_docs)

[[  0   0 257 251  85  56 223 186]
 [  0   0  78 201  85 348  70 211]
 [  0   0   0   0 469 175 240 169]
 [  0   0 257 121  85  82 257 346]
 [  0  44 187 424  85 348  70 211]
 [  0   0 488  85 348  70 177 288]]


In [41]:
## 10 feature dimesnions
embedded_vector_size=10

In [54]:
model = Sequential()
model.add(Embedding(voc_size, embedded_vector_size,input_shape=(sent_length,)))
model.compile(optimizer='adam', loss='mse')


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [55]:
model.summary()

Model: "sequential_16"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_13 (Embedding)        │ (None, 8, 10)          │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [57]:
#The world is a better place
embedded_docs[0]

array([  0,   0, 257, 251,  85,  56, 223, 186], dtype=int32)

In [59]:
model.predict(np.array([embedded_docs[0]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step


array([[[-0.01652237, -0.02707862,  0.04576821, -0.02202795,
          0.0033007 , -0.00192076,  0.04730621, -0.0342581 ,
         -0.03830659, -0.00845622],
        [-0.01652237, -0.02707862,  0.04576821, -0.02202795,
          0.0033007 , -0.00192076,  0.04730621, -0.0342581 ,
         -0.03830659, -0.00845622],
        [ 0.03682784, -0.03601338, -0.01777239, -0.0160936 ,
          0.0044561 ,  0.03890815, -0.0166141 ,  0.01306112,
          0.01354002, -0.04067151],
        [ 0.00800214,  0.04850599,  0.00721656,  0.01532287,
         -0.00478878,  0.04521171, -0.03080991, -0.00036003,
         -0.01771525,  0.03146398],
        [-0.03884908, -0.04361233,  0.01271698, -0.01076504,
         -0.00937548, -0.01057751,  0.02311165, -0.00848808,
         -0.00139811, -0.01825937],
        [ 0.02724079, -0.02899205,  0.03756764, -0.0020768 ,
          0.04412803,  0.00500502,  0.02248311,  0.03347499,
         -0.01311658, -0.0172801 ],
        [-0.0423183 ,  0.03584209,  0.02773157, -0.0

In [60]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
[[[-1.65223703e-02 -2.70786174e-02  4.57682125e-02 -2.20279451e-02
    3.30070406e-03 -1.92075968e-03  4.73062135e-02 -3.42581049e-02
   -3.83065939e-02 -8.45621899e-03]
  [-1.65223703e-02 -2.70786174e-02  4.57682125e-02 -2.20279451e-02
    3.30070406e-03 -1.92075968e-03  4.73062135e-02 -3.42581049e-02
   -3.83065939e-02 -8.45621899e-03]
  [ 3.68278362e-02 -3.60133760e-02 -1.77723877e-02 -1.60936005e-02
    4.45610285e-03  3.89081500e-02 -1.66141018e-02  1.30611174e-02
    1.35400183e-02 -4.06715050e-02]
  [ 8.00213963e-03  4.85059880e-02  7.21656159e-03  1.53228678e-02
   -4.78877872e-03  4.52117063e-02 -3.08099147e-02 -3.60034406e-04
   -1.77152529e-02  3.14639844e-02]
  [-3.88490781e-02 -4.36123274e-02  1.27169751e-02 -1.07650384e-02
   -9.37547535e-03 -1.05775110e-02  2.31116451e-02 -8.48808140e-03
   -1.39810890e-03 -1.82593688e-02]
  [ 2.72407867e-02 -2.89920457e-02  3.75676416e-02 -2.07680464e-03
    4.41280268e-02  5.00502437e-03  2.2483114

In [62]:
weights = model.get_weights()[0]
len(weights)

500

In [63]:
# weights of cat
weights[121]

array([ 0.02760312,  0.01833877, -0.02614882, -0.008837  , -0.01659477,
       -0.02667425,  0.00044603, -0.01861606, -0.02839117,  0.01183337],
      dtype=float32)

In [64]:
#weights of tom
weights[44]

array([ 0.0114364 , -0.03000796, -0.04817628,  0.02005878,  0.00555822,
       -0.01723946,  0.01567015,  0.00147369,  0.02838692,  0.00581347],
      dtype=float32)